from django.db import models

from apps.core.crypto import decrypt_json, encrypt_json
from apps.core.models import TimeStampedModel


class AndroidSigningCredential(TimeStampedModel):
    app = models.OneToOneField(
        "publisher.MobileApp",
        related_name="android_signing",
        on_delete=models.CASCADE,
    )
    credential_blob = models.TextField()
    certificate_sha256 = models.CharField(max_length=128, blank=True)
    generated_automatically = models.BooleanField(default=True)

    class Meta:
        ordering = ["app__name"]

    def __str__(self):
        return f"Android upload key · {self.app.name}"

    def set_credentials(self, value: dict) -> None:
        self.credential_blob = encrypt_json(value)

    def get_credentials(self) -> dict:
        return decrypt_json(self.credential_blob)


class IOSDistributionCredential(TimeStampedModel):
    """Publisher-owned Apple Distribution keypair/certificate for one team.

    The private key is generated by Publisher and encrypted at rest. Apple only
    receives the CSR, so this is the credential Cloud Mac can actually import
    into an ephemeral keychain for App Store archives.
    """

    store_account = models.OneToOneField(
        "publisher.StoreAccount",
        related_name="ios_distribution_signing",
        on_delete=models.CASCADE,
        limit_choices_to={"provider": "apple"},
    )
    credential_blob = models.TextField()
    apple_certificate_id = models.CharField(max_length=120, unique=True)
    certificate_serial_number = models.CharField(max_length=160, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)
    generated_automatically = models.BooleanField(default=True)

    class Meta:
        ordering = ["store_account__name"]

    def __str__(self):
        return f"Apple Distribution · {self.store_account.name}"

    def set_credentials(self, value: dict) -> None:
        self.credential_blob = encrypt_json(value)

    def get_credentials(self) -> dict:
        return decrypt_json(self.credential_blob)


class IOSProvisioningProfile(TimeStampedModel):
    """App Store distribution profile for one mobile app."""

    app = models.OneToOneField(
        "publisher.MobileApp",
        related_name="ios_provisioning_profile",
        on_delete=models.CASCADE,
    )
    distribution_credential = models.ForeignKey(
        IOSDistributionCredential,
        related_name="profiles",
        on_delete=models.CASCADE,
    )
    credential_blob = models.TextField()
    apple_profile_id = models.CharField(max_length=120, unique=True)
    profile_name = models.CharField(max_length=240)
    profile_uuid = models.CharField(max_length=120, blank=True)
    expires_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["app__name"]

    def __str__(self):
        return f"iOS App Store profile · {self.app.name}"

    def set_credentials(self, value: dict) -> None:
        self.credential_blob = encrypt_json(value)

    def get_credentials(self) -> dict:
        return decrypt_json(self.credential_blob)
